# Autogenerated by nbdev

d = { 'settings': { 'branch': 'master',
                'doc_baseurl': '/stratgame_stgrad74',
                'doc_host': 'https://Gla55ba11Gamer.github.io',
                'git_url': 'https://github.com/Gla55ba11Gamer/stratgame_stgrad74',
                'lib_path': 'stratgame_stgrad74'},
  'syms': {'stratgame_stgrad74.core': {'stratgame_stgrad74.core.foo': ('core.html#foo', 'stratgame_stgrad74/core.py')}}}